"""add active field

Revision ID: 16c6cc7171bf
Revises: a717e92b5ae5
Create Date: 2021-11-15 11:00:15.970065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c6cc7171bf'
down_revision = 'a717e92b5ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'active')
    # ### end Alembic commands ###
