"""add county

Revision ID: 3981ca6ac2ef
Revises: d24ab4843b30
Create Date: 2021-11-15 11:08:35.729513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3981ca6ac2ef'
down_revision = 'd24ab4843b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('parish', sa.String(length=100), nullable=True))
    op.drop_column('places', 'district_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('district_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('places', 'parish')
    # ### end Alembic commands ###
