"""init migration

Revision ID: a717e92b5ae5
Revises: 
Create Date: 2021-11-15 10:48:05.293039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a717e92b5ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.Column('postcode_trim', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('easting', sa.Float(), nullable=True),
    sa.Column('northing', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('district_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('date_introduced', sa.DateTime(), nullable=True),
    sa.Column('date_terminated', sa.DateTime(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('households', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('nearest_train', sa.String(length=100), nullable=True),
    sa.Column('distance_to_train', sa.Float(), nullable=True),
    sa.Column('police', sa.String(length=100), nullable=True),
    sa.Column('plus_code', sa.String(length=100), nullable=True),
    sa.Column('average_income', sa.Float(), nullable=True),
    sa.Column('sewage_company', sa.String(length=100), nullable=True),
    sa.Column('water_company', sa.String(length=100), nullable=True),
    sa.Column('itl_one', sa.String(length=100), nullable=True),
    sa.Column('itl_two', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    # ### end Alembic commands ###
