"""add Request table

Revision ID: d5c3a9c3d70f
Revises: 3981ca6ac2ef
Create Date: 2021-11-17 22:40:26.419985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c3a9c3d70f'
down_revision = '3981ca6ac2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('full_url', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_gin', table_name='places')
    op.drop_index('idx_income', table_name='places')
    op.drop_index('idx_place_postcode', table_name='places')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_place_postcode', 'places', ['postcode', 'postcode_trim'], unique=False)
    op.create_index('idx_income', 'places', ['average_income'], unique=False)
    op.create_index('idx_gin', 'places', ['postcode'], unique=False)
    op.drop_table('request')
    # ### end Alembic commands ###
